name: Bug report
description: Report something that is broken or incorrect
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        **Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)
        detailing how to provide the necessary information for us to reproduce your bug. In brief:
          * Please provide exact steps how to reproduce the bug in a clean Python environment.
          * In case it's not clear what's causing this bug, please provide the data or the data generation procedure.
          * Replicate problems on public datasets or share data subsets when full sharing isn't possible.

  - type: textarea
    id: report
    attributes:
      label: Report
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: |
        Which version of packages.

        Please install `session-info2`, run the following command in a notebook,
        click the “Copy as Markdown” button, then paste the results into the text box below.

        ```python
        In[1]: import session_info2; session_info2.session_info(dependencies=True)
        ```

        Alternatively, run this in a console:

        ```python
        >>> import session_info2; print(session_info2.session_info(dependencies=True)._repr_mimebundle_()["text/markdown"])
        ```
      render: python
      placeholder: |
        pandas-uuid     0.1.0
        ----            ----
        numpy           2.3.5
        pandas          2.3.3
        pyarrow         22.0.0
        pyarrow-stubs   20.0.0.20251215
        python-dateutil 2.9.0.post0
        pytz            2025.2
        six             1.17.0
        tzdata          2025.3
        ----            ----
        Python	3.13.2 | packaged by conda-forge | (main, Feb 17 2025, 14:10:22) [GCC 13.3.0]
        OS	Linux-6.11.0-109019-tuxedo-x86_64-with-glibc2.39
        Updated	2025-03-18 15:47
